POST http://localhost:3000/auth/register
Content-Type: application/json

{
 "name": "Pedro",
 "lastname": "Lucas",
 "email": "perolucas6@gmail.com",
 "password": "teste123"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
 "email": "pedrolucas6@gmail.com",
 "password": "teste123"
}

###

GET http://localhost:3000/users/e2532ce7-d6bc-4d27-8e6f-c91ff3447b46
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImUyNTMyY2U3LWQ2YmMtNGQyNy04ZTZmLWM5MWZmMzQ0N2I0NiIsIm5hbWUiOiJQZWRybyIsImxhc3RuYW1lIjoiTHVjYXMiLCJpYXQiOjE3Njc5OTQ5NzF9.-cXQ68Ne4fx2sYrmDXfBO8BcahhBKtHtzImQ2qN6DNA

###

GET http://localhost:10000/products?q=casacos&page=1

###

GET http://localhost:3000/products/dd5dadf7-16ce-4e52-bbfd-efb036073e7

###

GET http://localhost:10000/products/featured